"""initial schema

Revision ID: 3b97032df62f
Revises: 
Create Date: 2026-04-19 10:26:22.344824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b97032df62f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('latest_period', sa.String(), nullable=True),
    sa.Column('yoy_period', sa.String(), nullable=True),
    sa.Column('financial_summary', sa.Text(), nullable=True),
    sa.Column('raw_metrics_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'as_of', name='uq_fin_code_asof')
    )
    op.create_table('holder_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('smart_money_pct', sa.Float(), nullable=True),
    sa.Column('state_pct', sa.Float(), nullable=True),
    sa.Column('foreign_pct', sa.Float(), nullable=True),
    sa.Column('holder_structure', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'as_of', name='uq_hold_code_asof')
    )
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index('ix_news_source_pub', 'news_items', ['source', 'published_at'], unique=False)
    op.create_table('technical_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('ma20', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.String(), nullable=True),
    sa.Column('technical_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'as_of', name='uq_tech_code_asof')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('recommendation_threshold', sa.Float(), nullable=False),
    sa.Column('trading_style', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('conditions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('condition_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('layer', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('keywords_json', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'condition_id', name='uq_conditions_user_condition')
    )
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('trigger_key', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('langsmith_project', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_outputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'agent_name', 'sequence', name='uq_agent_outputs')
    )
    op.create_index('ix_agent_outputs_name_time', 'agent_outputs', ['agent_name', 'created_at'], unique=False)
    op.create_table('triggers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trigger_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('strength', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('source_news_ids', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trigger_id')
    )
    op.create_table('stock_data_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_output_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('leadership', sa.Text(), nullable=True),
    sa.Column('holder_structure', sa.Text(), nullable=True),
    sa.Column('financial_summary', sa.Text(), nullable=True),
    sa.Column('technical_summary', sa.Text(), nullable=True),
    sa.Column('price_benefit', sa.Text(), nullable=True),
    sa.Column('data_gaps_json', sa.Text(), nullable=True),
    sa.Column('sources_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_output_id'], ['agent_outputs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_output_id', 'code', name='uq_sde_agent_code')
    )
    op.create_index('ix_sde_code_time', 'stock_data_entries', ['code', 'created_at'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_output_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('args_json', sa.Text(), nullable=False),
    sa.Column('stock_code', sa.String(), nullable=True),
    sa.Column('result_preview', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_output_id'], ['agent_outputs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tc_agent_seq', 'tool_calls', ['agent_output_id', 'sequence'], unique=False)
    op.create_index('ix_tc_code_time', 'tool_calls', ['stock_code', 'created_at'], unique=False)
    op.create_table('stock_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_output_id', sa.Integer(), nullable=False),
    sa.Column('stock_data_entry_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('recommendation_level', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('recommendation_rationale', sa.Text(), nullable=True),
    sa.Column('key_strengths_json', sa.Text(), nullable=True),
    sa.Column('key_risks_json', sa.Text(), nullable=True),
    sa.Column('data_gaps_json', sa.Text(), nullable=True),
    sa.Column('trigger_ref', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_output_id'], ['agent_outputs.id'], ),
    sa.ForeignKeyConstraint(['stock_data_entry_id'], ['stock_data_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sr_agent_rank', 'stock_recommendations', ['agent_output_id', 'rank'], unique=False)
    op.create_index('ix_sr_code_time', 'stock_recommendations', ['code', 'created_at'], unique=False)
    op.create_table('condition_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_recommendation_id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.String(), nullable=False),
    sa.Column('condition_name', sa.String(), nullable=False),
    sa.Column('satisfaction', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('weighted_score', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stock_recommendation_id'], ['stock_recommendations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_recommendation_id', 'condition_id', name='uq_cs_rec_cond')
    )
    op.create_table('skeptic_findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_output_id', sa.Integer(), nullable=False),
    sa.Column('stock_recommendation_id', sa.Integer(), nullable=True),
    sa.Column('stock_code', sa.String(), nullable=False),
    sa.Column('finding_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_output_id'], ['agent_outputs.id'], ),
    sa.ForeignKeyConstraint(['stock_recommendation_id'], ['stock_recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sf_agent_code', 'skeptic_findings', ['agent_output_id', 'stock_code'], unique=False)
    op.create_index('ix_sf_rec', 'skeptic_findings', ['stock_recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sf_rec', table_name='skeptic_findings')
    op.drop_index('ix_sf_agent_code', table_name='skeptic_findings')
    op.drop_table('skeptic_findings')
    op.drop_table('condition_scores')
    op.drop_index('ix_sr_code_time', table_name='stock_recommendations')
    op.drop_index('ix_sr_agent_rank', table_name='stock_recommendations')
    op.drop_table('stock_recommendations')
    op.drop_index('ix_tc_code_time', table_name='tool_calls')
    op.drop_index('ix_tc_agent_seq', table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index('ix_sde_code_time', table_name='stock_data_entries')
    op.drop_table('stock_data_entries')
    op.drop_table('triggers')
    op.drop_index('ix_agent_outputs_name_time', table_name='agent_outputs')
    op.drop_table('agent_outputs')
    op.drop_table('runs')
    op.drop_table('conditions')
    op.drop_table('users')
    op.drop_table('technical_snapshots')
    op.drop_index('ix_news_source_pub', table_name='news_items')
    op.drop_table('news_items')
    op.drop_table('holder_snapshots')
    op.drop_table('financial_snapshots')
    # ### end Alembic commands ###
