"""add prompt_versions table

Revision ID: 8092f05d1359
Revises: 39227475371b
Create Date: 2026-04-19 17:26:44.754988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8092f05d1359'
down_revision: Union[str, Sequence[str], None] = '39227475371b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('version_code', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_name', 'version_code', name='uq_prompt_agent_version')
    )
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.create_index('ix_prompt_agent_active', ['agent_name', 'is_active'], unique=False)
        batch_op.create_index('ix_prompt_created', ['agent_name', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_prompt_created')
        batch_op.drop_index('ix_prompt_agent_active')

    op.drop_table('prompt_versions')
    # ### end Alembic commands ###
